var a = "test",
    b = "test",
    c = "test";
console.log('a = '+a);
console.log('b = '+b);
console.log('c = '+c);
a = "PI";
b = "test";
c = "completed";
console.log('a = '+a);
console.log('b = '+b);
console.log("c = "+c);
